name: Release Drafter

on:
  workflow_call:

permissions:
  contents: read

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    name: Create draft release
    permissions:
      contents: write
      pull-requests: write

    outputs:
      release: ${{ steps.create-draft-release.outputs.tag_name }}

    steps:
      # Drafts your next Release notes as Pull Requests are merged in
      - uses: release-drafter/release-drafter@v5
        id: create-draft-release
        with:
          commitish: ${{ github.event.pull_request.base.ref }}
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-branch:
    # Only run this job if the PR was merged
    if: github.event.pull_request.merged == true

    name: Create release branch
    needs: [create-draft-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Create a release branch
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/${{ needs.create-draft-release.outputs.release }}

      # Comment on the PR with the release branch link
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            The release branch (${{ needs.create-draft-release.outputs.release }}) for this PR has been created at ${{ github.event.pull_request.base.repo.html_url }}/tree/release/${{ needs.create-draft-release.outputs.release }}
